<?php
/**
 * AuthorizationLinks
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;
/**
 * AuthorizationLinks Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     CyberSource
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthorizationLinks implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'self' => '\CyberSource\Model\Link',
        'auth_reversal' => '\CyberSource\Model\Link',
        'capture' => '\CyberSource\Model\Link'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'self' => 'self',
        'auth_reversal' => 'authReversal',
        'capture' => 'capture'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'self' => 'setSelf',
        'auth_reversal' => 'setAuthReversal',
        'capture' => 'setCapture'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'self' => 'getSelf',
        'auth_reversal' => 'getAuthReversal',
        'capture' => 'getCapture'
    );
  
    
    /**
      * $self 
      * @var \CyberSource\Model\Link
      */
    protected $self;
    
    /**
      * $auth_reversal 
      * @var \CyberSource\Model\Link
      */
    protected $auth_reversal;
    
    /**
      * $capture 
      * @var \CyberSource\Model\Link
      */
    protected $capture;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->self = $data["self"];
            $this->auth_reversal = $data["auth_reversal"];
            $this->capture = $data["capture"];
        }
    }
    
    /**
     * Gets self
     * @return \CyberSource\Model\Link
     */
    public function getSelf()
    {
        return $this->self;
    }
  
    /**
     * Sets self
     * @param \CyberSource\Model\Link $self 
     * @return $this
     */
    public function setSelf($self)
    {
        
        $this->self = $self;
        return $this;
    }
    
    /**
     * Gets auth_reversal
     * @return \CyberSource\Model\Link
     */
    public function getAuthReversal()
    {
        return $this->auth_reversal;
    }
  
    /**
     * Sets auth_reversal
     * @param \CyberSource\Model\Link $auth_reversal 
     * @return $this
     */
    public function setAuthReversal($auth_reversal)
    {
        
        $this->auth_reversal = $auth_reversal;
        return $this;
    }
    
    /**
     * Gets capture
     * @return \CyberSource\Model\Link
     */
    public function getCapture()
    {
        return $this->capture;
    }
  
    /**
     * Sets capture
     * @param \CyberSource\Model\Link $capture 
     * @return $this
     */
    public function setCapture($capture)
    {
        
        $this->capture = $capture;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
