<?php
/**
 * MerchantDefinedData
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;
/**
 * MerchantDefinedData Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     CyberSource
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MerchantDefinedData implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'field1' => 'string',
        'field2' => 'string',
        'field3' => 'string',
        'field4' => 'string',
        'field5' => 'string',
        'field6' => 'string',
        'field7' => 'string',
        'field8' => 'string',
        'field9' => 'string',
        'field10' => 'string',
        'field11' => 'string',
        'field12' => 'string',
        'field13' => 'string',
        'field14' => 'string',
        'field15' => 'string',
        'field16' => 'string',
        'field17' => 'string',
        'field18' => 'string',
        'field19' => 'string',
        'field20' => 'string',
        'field21' => 'string',
        'field22' => 'string',
        'field23' => 'string',
        'field24' => 'string',
        'field25' => 'string',
        'field26' => 'string',
        'field27' => 'string',
        'field28' => 'string',
        'field29' => 'string',
        'field30' => 'string',
        'field31' => 'string',
        'field32' => 'string',
        'field33' => 'string',
        'field34' => 'string',
        'field35' => 'string',
        'field36' => 'string',
        'field37' => 'string',
        'field38' => 'string',
        'field39' => 'string',
        'field40' => 'string',
        'field41' => 'string',
        'field42' => 'string',
        'field43' => 'string',
        'field44' => 'string',
        'field45' => 'string',
        'field46' => 'string',
        'field47' => 'string',
        'field48' => 'string',
        'field49' => 'string',
        'field50' => 'string',
        'field51' => 'string',
        'field52' => 'string',
        'field53' => 'string',
        'field54' => 'string',
        'field55' => 'string',
        'field56' => 'string',
        'field57' => 'string',
        'field58' => 'string',
        'field59' => 'string',
        'field60' => 'string',
        'field61' => 'string',
        'field62' => 'string',
        'field63' => 'string',
        'field64' => 'string',
        'field65' => 'string',
        'field66' => 'string',
        'field67' => 'string',
        'field68' => 'string',
        'field69' => 'string',
        'field70' => 'string',
        'field71' => 'string',
        'field72' => 'string',
        'field73' => 'string',
        'field74' => 'string',
        'field75' => 'string',
        'field76' => 'string',
        'field77' => 'string',
        'field78' => 'string',
        'field79' => 'string',
        'field80' => 'string',
        'field81' => 'string',
        'field82' => 'string',
        'field83' => 'string',
        'field84' => 'string',
        'field85' => 'string',
        'field86' => 'string',
        'field87' => 'string',
        'field88' => 'string',
        'field89' => 'string',
        'field90' => 'string',
        'field91' => 'string',
        'field92' => 'string',
        'field93' => 'string',
        'field94' => 'string',
        'field95' => 'string',
        'field96' => 'string',
        'field97' => 'string',
        'field98' => 'string',
        'field99' => 'string',
        'field100' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'field1' => 'field1',
        'field2' => 'field2',
        'field3' => 'field3',
        'field4' => 'field4',
        'field5' => 'field5',
        'field6' => 'field6',
        'field7' => 'field7',
        'field8' => 'field8',
        'field9' => 'field9',
        'field10' => 'field10',
        'field11' => 'field11',
        'field12' => 'field12',
        'field13' => 'field13',
        'field14' => 'field14',
        'field15' => 'field15',
        'field16' => 'field16',
        'field17' => 'field17',
        'field18' => 'field18',
        'field19' => 'field19',
        'field20' => 'field20',
        'field21' => 'field21',
        'field22' => 'field22',
        'field23' => 'field23',
        'field24' => 'field24',
        'field25' => 'field25',
        'field26' => 'field26',
        'field27' => 'field27',
        'field28' => 'field28',
        'field29' => 'field29',
        'field30' => 'field30',
        'field31' => 'field31',
        'field32' => 'field32',
        'field33' => 'field33',
        'field34' => 'field34',
        'field35' => 'field35',
        'field36' => 'field36',
        'field37' => 'field37',
        'field38' => 'field38',
        'field39' => 'field39',
        'field40' => 'field40',
        'field41' => 'field41',
        'field42' => 'field42',
        'field43' => 'field43',
        'field44' => 'field44',
        'field45' => 'field45',
        'field46' => 'field46',
        'field47' => 'field47',
        'field48' => 'field48',
        'field49' => 'field49',
        'field50' => 'field50',
        'field51' => 'field51',
        'field52' => 'field52',
        'field53' => 'field53',
        'field54' => 'field54',
        'field55' => 'field55',
        'field56' => 'field56',
        'field57' => 'field57',
        'field58' => 'field58',
        'field59' => 'field59',
        'field60' => 'field60',
        'field61' => 'field61',
        'field62' => 'field62',
        'field63' => 'field63',
        'field64' => 'field64',
        'field65' => 'field65',
        'field66' => 'field66',
        'field67' => 'field67',
        'field68' => 'field68',
        'field69' => 'field69',
        'field70' => 'field70',
        'field71' => 'field71',
        'field72' => 'field72',
        'field73' => 'field73',
        'field74' => 'field74',
        'field75' => 'field75',
        'field76' => 'field76',
        'field77' => 'field77',
        'field78' => 'field78',
        'field79' => 'field79',
        'field80' => 'field80',
        'field81' => 'field81',
        'field82' => 'field82',
        'field83' => 'field83',
        'field84' => 'field84',
        'field85' => 'field85',
        'field86' => 'field86',
        'field87' => 'field87',
        'field88' => 'field88',
        'field89' => 'field89',
        'field90' => 'field90',
        'field91' => 'field91',
        'field92' => 'field92',
        'field93' => 'field93',
        'field94' => 'field94',
        'field95' => 'field95',
        'field96' => 'field96',
        'field97' => 'field97',
        'field98' => 'field98',
        'field99' => 'field99',
        'field100' => 'field100'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'field1' => 'setField1',
        'field2' => 'setField2',
        'field3' => 'setField3',
        'field4' => 'setField4',
        'field5' => 'setField5',
        'field6' => 'setField6',
        'field7' => 'setField7',
        'field8' => 'setField8',
        'field9' => 'setField9',
        'field10' => 'setField10',
        'field11' => 'setField11',
        'field12' => 'setField12',
        'field13' => 'setField13',
        'field14' => 'setField14',
        'field15' => 'setField15',
        'field16' => 'setField16',
        'field17' => 'setField17',
        'field18' => 'setField18',
        'field19' => 'setField19',
        'field20' => 'setField20',
        'field21' => 'setField21',
        'field22' => 'setField22',
        'field23' => 'setField23',
        'field24' => 'setField24',
        'field25' => 'setField25',
        'field26' => 'setField26',
        'field27' => 'setField27',
        'field28' => 'setField28',
        'field29' => 'setField29',
        'field30' => 'setField30',
        'field31' => 'setField31',
        'field32' => 'setField32',
        'field33' => 'setField33',
        'field34' => 'setField34',
        'field35' => 'setField35',
        'field36' => 'setField36',
        'field37' => 'setField37',
        'field38' => 'setField38',
        'field39' => 'setField39',
        'field40' => 'setField40',
        'field41' => 'setField41',
        'field42' => 'setField42',
        'field43' => 'setField43',
        'field44' => 'setField44',
        'field45' => 'setField45',
        'field46' => 'setField46',
        'field47' => 'setField47',
        'field48' => 'setField48',
        'field49' => 'setField49',
        'field50' => 'setField50',
        'field51' => 'setField51',
        'field52' => 'setField52',
        'field53' => 'setField53',
        'field54' => 'setField54',
        'field55' => 'setField55',
        'field56' => 'setField56',
        'field57' => 'setField57',
        'field58' => 'setField58',
        'field59' => 'setField59',
        'field60' => 'setField60',
        'field61' => 'setField61',
        'field62' => 'setField62',
        'field63' => 'setField63',
        'field64' => 'setField64',
        'field65' => 'setField65',
        'field66' => 'setField66',
        'field67' => 'setField67',
        'field68' => 'setField68',
        'field69' => 'setField69',
        'field70' => 'setField70',
        'field71' => 'setField71',
        'field72' => 'setField72',
        'field73' => 'setField73',
        'field74' => 'setField74',
        'field75' => 'setField75',
        'field76' => 'setField76',
        'field77' => 'setField77',
        'field78' => 'setField78',
        'field79' => 'setField79',
        'field80' => 'setField80',
        'field81' => 'setField81',
        'field82' => 'setField82',
        'field83' => 'setField83',
        'field84' => 'setField84',
        'field85' => 'setField85',
        'field86' => 'setField86',
        'field87' => 'setField87',
        'field88' => 'setField88',
        'field89' => 'setField89',
        'field90' => 'setField90',
        'field91' => 'setField91',
        'field92' => 'setField92',
        'field93' => 'setField93',
        'field94' => 'setField94',
        'field95' => 'setField95',
        'field96' => 'setField96',
        'field97' => 'setField97',
        'field98' => 'setField98',
        'field99' => 'setField99',
        'field100' => 'setField100'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'field1' => 'getField1',
        'field2' => 'getField2',
        'field3' => 'getField3',
        'field4' => 'getField4',
        'field5' => 'getField5',
        'field6' => 'getField6',
        'field7' => 'getField7',
        'field8' => 'getField8',
        'field9' => 'getField9',
        'field10' => 'getField10',
        'field11' => 'getField11',
        'field12' => 'getField12',
        'field13' => 'getField13',
        'field14' => 'getField14',
        'field15' => 'getField15',
        'field16' => 'getField16',
        'field17' => 'getField17',
        'field18' => 'getField18',
        'field19' => 'getField19',
        'field20' => 'getField20',
        'field21' => 'getField21',
        'field22' => 'getField22',
        'field23' => 'getField23',
        'field24' => 'getField24',
        'field25' => 'getField25',
        'field26' => 'getField26',
        'field27' => 'getField27',
        'field28' => 'getField28',
        'field29' => 'getField29',
        'field30' => 'getField30',
        'field31' => 'getField31',
        'field32' => 'getField32',
        'field33' => 'getField33',
        'field34' => 'getField34',
        'field35' => 'getField35',
        'field36' => 'getField36',
        'field37' => 'getField37',
        'field38' => 'getField38',
        'field39' => 'getField39',
        'field40' => 'getField40',
        'field41' => 'getField41',
        'field42' => 'getField42',
        'field43' => 'getField43',
        'field44' => 'getField44',
        'field45' => 'getField45',
        'field46' => 'getField46',
        'field47' => 'getField47',
        'field48' => 'getField48',
        'field49' => 'getField49',
        'field50' => 'getField50',
        'field51' => 'getField51',
        'field52' => 'getField52',
        'field53' => 'getField53',
        'field54' => 'getField54',
        'field55' => 'getField55',
        'field56' => 'getField56',
        'field57' => 'getField57',
        'field58' => 'getField58',
        'field59' => 'getField59',
        'field60' => 'getField60',
        'field61' => 'getField61',
        'field62' => 'getField62',
        'field63' => 'getField63',
        'field64' => 'getField64',
        'field65' => 'getField65',
        'field66' => 'getField66',
        'field67' => 'getField67',
        'field68' => 'getField68',
        'field69' => 'getField69',
        'field70' => 'getField70',
        'field71' => 'getField71',
        'field72' => 'getField72',
        'field73' => 'getField73',
        'field74' => 'getField74',
        'field75' => 'getField75',
        'field76' => 'getField76',
        'field77' => 'getField77',
        'field78' => 'getField78',
        'field79' => 'getField79',
        'field80' => 'getField80',
        'field81' => 'getField81',
        'field82' => 'getField82',
        'field83' => 'getField83',
        'field84' => 'getField84',
        'field85' => 'getField85',
        'field86' => 'getField86',
        'field87' => 'getField87',
        'field88' => 'getField88',
        'field89' => 'getField89',
        'field90' => 'getField90',
        'field91' => 'getField91',
        'field92' => 'getField92',
        'field93' => 'getField93',
        'field94' => 'getField94',
        'field95' => 'getField95',
        'field96' => 'getField96',
        'field97' => 'getField97',
        'field98' => 'getField98',
        'field99' => 'getField99',
        'field100' => 'getField100'
    );
  
    
    /**
      * $field1 Merchant defined field.
      * @var string
      */
    protected $field1;
    
    /**
      * $field2 Merchant defined field.
      * @var string
      */
    protected $field2;
    
    /**
      * $field3 Merchant defined field.
      * @var string
      */
    protected $field3;
    
    /**
      * $field4 Merchant defined field.
      * @var string
      */
    protected $field4;
    
    /**
      * $field5 Merchant defined field.
      * @var string
      */
    protected $field5;
    
    /**
      * $field6 Merchant defined field.
      * @var string
      */
    protected $field6;
    
    /**
      * $field7 Merchant defined field.
      * @var string
      */
    protected $field7;
    
    /**
      * $field8 Merchant defined field.
      * @var string
      */
    protected $field8;
    
    /**
      * $field9 Merchant defined field.
      * @var string
      */
    protected $field9;
    
    /**
      * $field10 Merchant defined field.
      * @var string
      */
    protected $field10;
    
    /**
      * $field11 Merchant defined field.
      * @var string
      */
    protected $field11;
    
    /**
      * $field12 Merchant defined field.
      * @var string
      */
    protected $field12;
    
    /**
      * $field13 Merchant defined field.
      * @var string
      */
    protected $field13;
    
    /**
      * $field14 Merchant defined field.
      * @var string
      */
    protected $field14;
    
    /**
      * $field15 Merchant defined field.
      * @var string
      */
    protected $field15;
    
    /**
      * $field16 Merchant defined field.
      * @var string
      */
    protected $field16;
    
    /**
      * $field17 Merchant defined field.
      * @var string
      */
    protected $field17;
    
    /**
      * $field18 Merchant defined field.
      * @var string
      */
    protected $field18;
    
    /**
      * $field19 Merchant defined field.
      * @var string
      */
    protected $field19;
    
    /**
      * $field20 Merchant defined field.
      * @var string
      */
    protected $field20;
    
    /**
      * $field21 Merchant defined field.
      * @var string
      */
    protected $field21;
    
    /**
      * $field22 Merchant defined field.
      * @var string
      */
    protected $field22;
    
    /**
      * $field23 Merchant defined field.
      * @var string
      */
    protected $field23;
    
    /**
      * $field24 Merchant defined field.
      * @var string
      */
    protected $field24;
    
    /**
      * $field25 Merchant defined field.
      * @var string
      */
    protected $field25;
    
    /**
      * $field26 Merchant defined field.
      * @var string
      */
    protected $field26;
    
    /**
      * $field27 Merchant defined field.
      * @var string
      */
    protected $field27;
    
    /**
      * $field28 Merchant defined field.
      * @var string
      */
    protected $field28;
    
    /**
      * $field29 Merchant defined field.
      * @var string
      */
    protected $field29;
    
    /**
      * $field30 Merchant defined field.
      * @var string
      */
    protected $field30;
    
    /**
      * $field31 Merchant defined field.
      * @var string
      */
    protected $field31;
    
    /**
      * $field32 Merchant defined field.
      * @var string
      */
    protected $field32;
    
    /**
      * $field33 Merchant defined field.
      * @var string
      */
    protected $field33;
    
    /**
      * $field34 Merchant defined field.
      * @var string
      */
    protected $field34;
    
    /**
      * $field35 Merchant defined field.
      * @var string
      */
    protected $field35;
    
    /**
      * $field36 Merchant defined field.
      * @var string
      */
    protected $field36;
    
    /**
      * $field37 Merchant defined field.
      * @var string
      */
    protected $field37;
    
    /**
      * $field38 Merchant defined field.
      * @var string
      */
    protected $field38;
    
    /**
      * $field39 Merchant defined field.
      * @var string
      */
    protected $field39;
    
    /**
      * $field40 Merchant defined field.
      * @var string
      */
    protected $field40;
    
    /**
      * $field41 Merchant defined field.
      * @var string
      */
    protected $field41;
    
    /**
      * $field42 Merchant defined field.
      * @var string
      */
    protected $field42;
    
    /**
      * $field43 Merchant defined field.
      * @var string
      */
    protected $field43;
    
    /**
      * $field44 Merchant defined field.
      * @var string
      */
    protected $field44;
    
    /**
      * $field45 Merchant defined field.
      * @var string
      */
    protected $field45;
    
    /**
      * $field46 Merchant defined field.
      * @var string
      */
    protected $field46;
    
    /**
      * $field47 Merchant defined field.
      * @var string
      */
    protected $field47;
    
    /**
      * $field48 Merchant defined field.
      * @var string
      */
    protected $field48;
    
    /**
      * $field49 Merchant defined field.
      * @var string
      */
    protected $field49;
    
    /**
      * $field50 Merchant defined field.
      * @var string
      */
    protected $field50;
    
    /**
      * $field51 Merchant defined field.
      * @var string
      */
    protected $field51;
    
    /**
      * $field52 Merchant defined field.
      * @var string
      */
    protected $field52;
    
    /**
      * $field53 Merchant defined field.
      * @var string
      */
    protected $field53;
    
    /**
      * $field54 Merchant defined field.
      * @var string
      */
    protected $field54;
    
    /**
      * $field55 Merchant defined field.
      * @var string
      */
    protected $field55;
    
    /**
      * $field56 Merchant defined field.
      * @var string
      */
    protected $field56;
    
    /**
      * $field57 Merchant defined field.
      * @var string
      */
    protected $field57;
    
    /**
      * $field58 Merchant defined field.
      * @var string
      */
    protected $field58;
    
    /**
      * $field59 Merchant defined field.
      * @var string
      */
    protected $field59;
    
    /**
      * $field60 Merchant defined field.
      * @var string
      */
    protected $field60;
    
    /**
      * $field61 Merchant defined field.
      * @var string
      */
    protected $field61;
    
    /**
      * $field62 Merchant defined field.
      * @var string
      */
    protected $field62;
    
    /**
      * $field63 Merchant defined field.
      * @var string
      */
    protected $field63;
    
    /**
      * $field64 Merchant defined field.
      * @var string
      */
    protected $field64;
    
    /**
      * $field65 Merchant defined field.
      * @var string
      */
    protected $field65;
    
    /**
      * $field66 Merchant defined field.
      * @var string
      */
    protected $field66;
    
    /**
      * $field67 Merchant defined field.
      * @var string
      */
    protected $field67;
    
    /**
      * $field68 Merchant defined field.
      * @var string
      */
    protected $field68;
    
    /**
      * $field69 Merchant defined field.
      * @var string
      */
    protected $field69;
    
    /**
      * $field70 Merchant defined field.
      * @var string
      */
    protected $field70;
    
    /**
      * $field71 Merchant defined field.
      * @var string
      */
    protected $field71;
    
    /**
      * $field72 Merchant defined field.
      * @var string
      */
    protected $field72;
    
    /**
      * $field73 Merchant defined field.
      * @var string
      */
    protected $field73;
    
    /**
      * $field74 Merchant defined field.
      * @var string
      */
    protected $field74;
    
    /**
      * $field75 Merchant defined field.
      * @var string
      */
    protected $field75;
    
    /**
      * $field76 Merchant defined field.
      * @var string
      */
    protected $field76;
    
    /**
      * $field77 Merchant defined field.
      * @var string
      */
    protected $field77;
    
    /**
      * $field78 Merchant defined field.
      * @var string
      */
    protected $field78;
    
    /**
      * $field79 Merchant defined field.
      * @var string
      */
    protected $field79;
    
    /**
      * $field80 Merchant defined field.
      * @var string
      */
    protected $field80;
    
    /**
      * $field81 Merchant defined field.
      * @var string
      */
    protected $field81;
    
    /**
      * $field82 Merchant defined field.
      * @var string
      */
    protected $field82;
    
    /**
      * $field83 Merchant defined field.
      * @var string
      */
    protected $field83;
    
    /**
      * $field84 Merchant defined field.
      * @var string
      */
    protected $field84;
    
    /**
      * $field85 Merchant defined field.
      * @var string
      */
    protected $field85;
    
    /**
      * $field86 Merchant defined field.
      * @var string
      */
    protected $field86;
    
    /**
      * $field87 Merchant defined field.
      * @var string
      */
    protected $field87;
    
    /**
      * $field88 Merchant defined field.
      * @var string
      */
    protected $field88;
    
    /**
      * $field89 Merchant defined field.
      * @var string
      */
    protected $field89;
    
    /**
      * $field90 Merchant defined field.
      * @var string
      */
    protected $field90;
    
    /**
      * $field91 Merchant defined field.
      * @var string
      */
    protected $field91;
    
    /**
      * $field92 Merchant defined field.
      * @var string
      */
    protected $field92;
    
    /**
      * $field93 Merchant defined field.
      * @var string
      */
    protected $field93;
    
    /**
      * $field94 Merchant defined field.
      * @var string
      */
    protected $field94;
    
    /**
      * $field95 Merchant defined field.
      * @var string
      */
    protected $field95;
    
    /**
      * $field96 Merchant defined field.
      * @var string
      */
    protected $field96;
    
    /**
      * $field97 Merchant defined field.
      * @var string
      */
    protected $field97;
    
    /**
      * $field98 Merchant defined field.
      * @var string
      */
    protected $field98;
    
    /**
      * $field99 Merchant defined field.
      * @var string
      */
    protected $field99;
    
    /**
      * $field100 Merchant defined field.
      * @var string
      */
    protected $field100;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->field1 = $data["field1"];
            $this->field2 = $data["field2"];
            $this->field3 = $data["field3"];
            $this->field4 = $data["field4"];
            $this->field5 = $data["field5"];
            $this->field6 = $data["field6"];
            $this->field7 = $data["field7"];
            $this->field8 = $data["field8"];
            $this->field9 = $data["field9"];
            $this->field10 = $data["field10"];
            $this->field11 = $data["field11"];
            $this->field12 = $data["field12"];
            $this->field13 = $data["field13"];
            $this->field14 = $data["field14"];
            $this->field15 = $data["field15"];
            $this->field16 = $data["field16"];
            $this->field17 = $data["field17"];
            $this->field18 = $data["field18"];
            $this->field19 = $data["field19"];
            $this->field20 = $data["field20"];
            $this->field21 = $data["field21"];
            $this->field22 = $data["field22"];
            $this->field23 = $data["field23"];
            $this->field24 = $data["field24"];
            $this->field25 = $data["field25"];
            $this->field26 = $data["field26"];
            $this->field27 = $data["field27"];
            $this->field28 = $data["field28"];
            $this->field29 = $data["field29"];
            $this->field30 = $data["field30"];
            $this->field31 = $data["field31"];
            $this->field32 = $data["field32"];
            $this->field33 = $data["field33"];
            $this->field34 = $data["field34"];
            $this->field35 = $data["field35"];
            $this->field36 = $data["field36"];
            $this->field37 = $data["field37"];
            $this->field38 = $data["field38"];
            $this->field39 = $data["field39"];
            $this->field40 = $data["field40"];
            $this->field41 = $data["field41"];
            $this->field42 = $data["field42"];
            $this->field43 = $data["field43"];
            $this->field44 = $data["field44"];
            $this->field45 = $data["field45"];
            $this->field46 = $data["field46"];
            $this->field47 = $data["field47"];
            $this->field48 = $data["field48"];
            $this->field49 = $data["field49"];
            $this->field50 = $data["field50"];
            $this->field51 = $data["field51"];
            $this->field52 = $data["field52"];
            $this->field53 = $data["field53"];
            $this->field54 = $data["field54"];
            $this->field55 = $data["field55"];
            $this->field56 = $data["field56"];
            $this->field57 = $data["field57"];
            $this->field58 = $data["field58"];
            $this->field59 = $data["field59"];
            $this->field60 = $data["field60"];
            $this->field61 = $data["field61"];
            $this->field62 = $data["field62"];
            $this->field63 = $data["field63"];
            $this->field64 = $data["field64"];
            $this->field65 = $data["field65"];
            $this->field66 = $data["field66"];
            $this->field67 = $data["field67"];
            $this->field68 = $data["field68"];
            $this->field69 = $data["field69"];
            $this->field70 = $data["field70"];
            $this->field71 = $data["field71"];
            $this->field72 = $data["field72"];
            $this->field73 = $data["field73"];
            $this->field74 = $data["field74"];
            $this->field75 = $data["field75"];
            $this->field76 = $data["field76"];
            $this->field77 = $data["field77"];
            $this->field78 = $data["field78"];
            $this->field79 = $data["field79"];
            $this->field80 = $data["field80"];
            $this->field81 = $data["field81"];
            $this->field82 = $data["field82"];
            $this->field83 = $data["field83"];
            $this->field84 = $data["field84"];
            $this->field85 = $data["field85"];
            $this->field86 = $data["field86"];
            $this->field87 = $data["field87"];
            $this->field88 = $data["field88"];
            $this->field89 = $data["field89"];
            $this->field90 = $data["field90"];
            $this->field91 = $data["field91"];
            $this->field92 = $data["field92"];
            $this->field93 = $data["field93"];
            $this->field94 = $data["field94"];
            $this->field95 = $data["field95"];
            $this->field96 = $data["field96"];
            $this->field97 = $data["field97"];
            $this->field98 = $data["field98"];
            $this->field99 = $data["field99"];
            $this->field100 = $data["field100"];
        }
    }
    
    /**
     * Gets field1
     * @return string
     */
    public function getField1()
    {
        return $this->field1;
    }
  
    /**
     * Sets field1
     * @param string $field1 Merchant defined field.
     * @return $this
     */
    public function setField1($field1)
    {
        
        $this->field1 = $field1;
        return $this;
    }
    
    /**
     * Gets field2
     * @return string
     */
    public function getField2()
    {
        return $this->field2;
    }
  
    /**
     * Sets field2
     * @param string $field2 Merchant defined field.
     * @return $this
     */
    public function setField2($field2)
    {
        
        $this->field2 = $field2;
        return $this;
    }
    
    /**
     * Gets field3
     * @return string
     */
    public function getField3()
    {
        return $this->field3;
    }
  
    /**
     * Sets field3
     * @param string $field3 Merchant defined field.
     * @return $this
     */
    public function setField3($field3)
    {
        
        $this->field3 = $field3;
        return $this;
    }
    
    /**
     * Gets field4
     * @return string
     */
    public function getField4()
    {
        return $this->field4;
    }
  
    /**
     * Sets field4
     * @param string $field4 Merchant defined field.
     * @return $this
     */
    public function setField4($field4)
    {
        
        $this->field4 = $field4;
        return $this;
    }
    
    /**
     * Gets field5
     * @return string
     */
    public function getField5()
    {
        return $this->field5;
    }
  
    /**
     * Sets field5
     * @param string $field5 Merchant defined field.
     * @return $this
     */
    public function setField5($field5)
    {
        
        $this->field5 = $field5;
        return $this;
    }
    
    /**
     * Gets field6
     * @return string
     */
    public function getField6()
    {
        return $this->field6;
    }
  
    /**
     * Sets field6
     * @param string $field6 Merchant defined field.
     * @return $this
     */
    public function setField6($field6)
    {
        
        $this->field6 = $field6;
        return $this;
    }
    
    /**
     * Gets field7
     * @return string
     */
    public function getField7()
    {
        return $this->field7;
    }
  
    /**
     * Sets field7
     * @param string $field7 Merchant defined field.
     * @return $this
     */
    public function setField7($field7)
    {
        
        $this->field7 = $field7;
        return $this;
    }
    
    /**
     * Gets field8
     * @return string
     */
    public function getField8()
    {
        return $this->field8;
    }
  
    /**
     * Sets field8
     * @param string $field8 Merchant defined field.
     * @return $this
     */
    public function setField8($field8)
    {
        
        $this->field8 = $field8;
        return $this;
    }
    
    /**
     * Gets field9
     * @return string
     */
    public function getField9()
    {
        return $this->field9;
    }
  
    /**
     * Sets field9
     * @param string $field9 Merchant defined field.
     * @return $this
     */
    public function setField9($field9)
    {
        
        $this->field9 = $field9;
        return $this;
    }
    
    /**
     * Gets field10
     * @return string
     */
    public function getField10()
    {
        return $this->field10;
    }
  
    /**
     * Sets field10
     * @param string $field10 Merchant defined field.
     * @return $this
     */
    public function setField10($field10)
    {
        
        $this->field10 = $field10;
        return $this;
    }
    
    /**
     * Gets field11
     * @return string
     */
    public function getField11()
    {
        return $this->field11;
    }
  
    /**
     * Sets field11
     * @param string $field11 Merchant defined field.
     * @return $this
     */
    public function setField11($field11)
    {
        
        $this->field11 = $field11;
        return $this;
    }
    
    /**
     * Gets field12
     * @return string
     */
    public function getField12()
    {
        return $this->field12;
    }
  
    /**
     * Sets field12
     * @param string $field12 Merchant defined field.
     * @return $this
     */
    public function setField12($field12)
    {
        
        $this->field12 = $field12;
        return $this;
    }
    
    /**
     * Gets field13
     * @return string
     */
    public function getField13()
    {
        return $this->field13;
    }
  
    /**
     * Sets field13
     * @param string $field13 Merchant defined field.
     * @return $this
     */
    public function setField13($field13)
    {
        
        $this->field13 = $field13;
        return $this;
    }
    
    /**
     * Gets field14
     * @return string
     */
    public function getField14()
    {
        return $this->field14;
    }
  
    /**
     * Sets field14
     * @param string $field14 Merchant defined field.
     * @return $this
     */
    public function setField14($field14)
    {
        
        $this->field14 = $field14;
        return $this;
    }
    
    /**
     * Gets field15
     * @return string
     */
    public function getField15()
    {
        return $this->field15;
    }
  
    /**
     * Sets field15
     * @param string $field15 Merchant defined field.
     * @return $this
     */
    public function setField15($field15)
    {
        
        $this->field15 = $field15;
        return $this;
    }
    
    /**
     * Gets field16
     * @return string
     */
    public function getField16()
    {
        return $this->field16;
    }
  
    /**
     * Sets field16
     * @param string $field16 Merchant defined field.
     * @return $this
     */
    public function setField16($field16)
    {
        
        $this->field16 = $field16;
        return $this;
    }
    
    /**
     * Gets field17
     * @return string
     */
    public function getField17()
    {
        return $this->field17;
    }
  
    /**
     * Sets field17
     * @param string $field17 Merchant defined field.
     * @return $this
     */
    public function setField17($field17)
    {
        
        $this->field17 = $field17;
        return $this;
    }
    
    /**
     * Gets field18
     * @return string
     */
    public function getField18()
    {
        return $this->field18;
    }
  
    /**
     * Sets field18
     * @param string $field18 Merchant defined field.
     * @return $this
     */
    public function setField18($field18)
    {
        
        $this->field18 = $field18;
        return $this;
    }
    
    /**
     * Gets field19
     * @return string
     */
    public function getField19()
    {
        return $this->field19;
    }
  
    /**
     * Sets field19
     * @param string $field19 Merchant defined field.
     * @return $this
     */
    public function setField19($field19)
    {
        
        $this->field19 = $field19;
        return $this;
    }
    
    /**
     * Gets field20
     * @return string
     */
    public function getField20()
    {
        return $this->field20;
    }
  
    /**
     * Sets field20
     * @param string $field20 Merchant defined field.
     * @return $this
     */
    public function setField20($field20)
    {
        
        $this->field20 = $field20;
        return $this;
    }
    
    /**
     * Gets field21
     * @return string
     */
    public function getField21()
    {
        return $this->field21;
    }
  
    /**
     * Sets field21
     * @param string $field21 Merchant defined field.
     * @return $this
     */
    public function setField21($field21)
    {
        
        $this->field21 = $field21;
        return $this;
    }
    
    /**
     * Gets field22
     * @return string
     */
    public function getField22()
    {
        return $this->field22;
    }
  
    /**
     * Sets field22
     * @param string $field22 Merchant defined field.
     * @return $this
     */
    public function setField22($field22)
    {
        
        $this->field22 = $field22;
        return $this;
    }
    
    /**
     * Gets field23
     * @return string
     */
    public function getField23()
    {
        return $this->field23;
    }
  
    /**
     * Sets field23
     * @param string $field23 Merchant defined field.
     * @return $this
     */
    public function setField23($field23)
    {
        
        $this->field23 = $field23;
        return $this;
    }
    
    /**
     * Gets field24
     * @return string
     */
    public function getField24()
    {
        return $this->field24;
    }
  
    /**
     * Sets field24
     * @param string $field24 Merchant defined field.
     * @return $this
     */
    public function setField24($field24)
    {
        
        $this->field24 = $field24;
        return $this;
    }
    
    /**
     * Gets field25
     * @return string
     */
    public function getField25()
    {
        return $this->field25;
    }
  
    /**
     * Sets field25
     * @param string $field25 Merchant defined field.
     * @return $this
     */
    public function setField25($field25)
    {
        
        $this->field25 = $field25;
        return $this;
    }
    
    /**
     * Gets field26
     * @return string
     */
    public function getField26()
    {
        return $this->field26;
    }
  
    /**
     * Sets field26
     * @param string $field26 Merchant defined field.
     * @return $this
     */
    public function setField26($field26)
    {
        
        $this->field26 = $field26;
        return $this;
    }
    
    /**
     * Gets field27
     * @return string
     */
    public function getField27()
    {
        return $this->field27;
    }
  
    /**
     * Sets field27
     * @param string $field27 Merchant defined field.
     * @return $this
     */
    public function setField27($field27)
    {
        
        $this->field27 = $field27;
        return $this;
    }
    
    /**
     * Gets field28
     * @return string
     */
    public function getField28()
    {
        return $this->field28;
    }
  
    /**
     * Sets field28
     * @param string $field28 Merchant defined field.
     * @return $this
     */
    public function setField28($field28)
    {
        
        $this->field28 = $field28;
        return $this;
    }
    
    /**
     * Gets field29
     * @return string
     */
    public function getField29()
    {
        return $this->field29;
    }
  
    /**
     * Sets field29
     * @param string $field29 Merchant defined field.
     * @return $this
     */
    public function setField29($field29)
    {
        
        $this->field29 = $field29;
        return $this;
    }
    
    /**
     * Gets field30
     * @return string
     */
    public function getField30()
    {
        return $this->field30;
    }
  
    /**
     * Sets field30
     * @param string $field30 Merchant defined field.
     * @return $this
     */
    public function setField30($field30)
    {
        
        $this->field30 = $field30;
        return $this;
    }
    
    /**
     * Gets field31
     * @return string
     */
    public function getField31()
    {
        return $this->field31;
    }
  
    /**
     * Sets field31
     * @param string $field31 Merchant defined field.
     * @return $this
     */
    public function setField31($field31)
    {
        
        $this->field31 = $field31;
        return $this;
    }
    
    /**
     * Gets field32
     * @return string
     */
    public function getField32()
    {
        return $this->field32;
    }
  
    /**
     * Sets field32
     * @param string $field32 Merchant defined field.
     * @return $this
     */
    public function setField32($field32)
    {
        
        $this->field32 = $field32;
        return $this;
    }
    
    /**
     * Gets field33
     * @return string
     */
    public function getField33()
    {
        return $this->field33;
    }
  
    /**
     * Sets field33
     * @param string $field33 Merchant defined field.
     * @return $this
     */
    public function setField33($field33)
    {
        
        $this->field33 = $field33;
        return $this;
    }
    
    /**
     * Gets field34
     * @return string
     */
    public function getField34()
    {
        return $this->field34;
    }
  
    /**
     * Sets field34
     * @param string $field34 Merchant defined field.
     * @return $this
     */
    public function setField34($field34)
    {
        
        $this->field34 = $field34;
        return $this;
    }
    
    /**
     * Gets field35
     * @return string
     */
    public function getField35()
    {
        return $this->field35;
    }
  
    /**
     * Sets field35
     * @param string $field35 Merchant defined field.
     * @return $this
     */
    public function setField35($field35)
    {
        
        $this->field35 = $field35;
        return $this;
    }
    
    /**
     * Gets field36
     * @return string
     */
    public function getField36()
    {
        return $this->field36;
    }
  
    /**
     * Sets field36
     * @param string $field36 Merchant defined field.
     * @return $this
     */
    public function setField36($field36)
    {
        
        $this->field36 = $field36;
        return $this;
    }
    
    /**
     * Gets field37
     * @return string
     */
    public function getField37()
    {
        return $this->field37;
    }
  
    /**
     * Sets field37
     * @param string $field37 Merchant defined field.
     * @return $this
     */
    public function setField37($field37)
    {
        
        $this->field37 = $field37;
        return $this;
    }
    
    /**
     * Gets field38
     * @return string
     */
    public function getField38()
    {
        return $this->field38;
    }
  
    /**
     * Sets field38
     * @param string $field38 Merchant defined field.
     * @return $this
     */
    public function setField38($field38)
    {
        
        $this->field38 = $field38;
        return $this;
    }
    
    /**
     * Gets field39
     * @return string
     */
    public function getField39()
    {
        return $this->field39;
    }
  
    /**
     * Sets field39
     * @param string $field39 Merchant defined field.
     * @return $this
     */
    public function setField39($field39)
    {
        
        $this->field39 = $field39;
        return $this;
    }
    
    /**
     * Gets field40
     * @return string
     */
    public function getField40()
    {
        return $this->field40;
    }
  
    /**
     * Sets field40
     * @param string $field40 Merchant defined field.
     * @return $this
     */
    public function setField40($field40)
    {
        
        $this->field40 = $field40;
        return $this;
    }
    
    /**
     * Gets field41
     * @return string
     */
    public function getField41()
    {
        return $this->field41;
    }
  
    /**
     * Sets field41
     * @param string $field41 Merchant defined field.
     * @return $this
     */
    public function setField41($field41)
    {
        
        $this->field41 = $field41;
        return $this;
    }
    
    /**
     * Gets field42
     * @return string
     */
    public function getField42()
    {
        return $this->field42;
    }
  
    /**
     * Sets field42
     * @param string $field42 Merchant defined field.
     * @return $this
     */
    public function setField42($field42)
    {
        
        $this->field42 = $field42;
        return $this;
    }
    
    /**
     * Gets field43
     * @return string
     */
    public function getField43()
    {
        return $this->field43;
    }
  
    /**
     * Sets field43
     * @param string $field43 Merchant defined field.
     * @return $this
     */
    public function setField43($field43)
    {
        
        $this->field43 = $field43;
        return $this;
    }
    
    /**
     * Gets field44
     * @return string
     */
    public function getField44()
    {
        return $this->field44;
    }
  
    /**
     * Sets field44
     * @param string $field44 Merchant defined field.
     * @return $this
     */
    public function setField44($field44)
    {
        
        $this->field44 = $field44;
        return $this;
    }
    
    /**
     * Gets field45
     * @return string
     */
    public function getField45()
    {
        return $this->field45;
    }
  
    /**
     * Sets field45
     * @param string $field45 Merchant defined field.
     * @return $this
     */
    public function setField45($field45)
    {
        
        $this->field45 = $field45;
        return $this;
    }
    
    /**
     * Gets field46
     * @return string
     */
    public function getField46()
    {
        return $this->field46;
    }
  
    /**
     * Sets field46
     * @param string $field46 Merchant defined field.
     * @return $this
     */
    public function setField46($field46)
    {
        
        $this->field46 = $field46;
        return $this;
    }
    
    /**
     * Gets field47
     * @return string
     */
    public function getField47()
    {
        return $this->field47;
    }
  
    /**
     * Sets field47
     * @param string $field47 Merchant defined field.
     * @return $this
     */
    public function setField47($field47)
    {
        
        $this->field47 = $field47;
        return $this;
    }
    
    /**
     * Gets field48
     * @return string
     */
    public function getField48()
    {
        return $this->field48;
    }
  
    /**
     * Sets field48
     * @param string $field48 Merchant defined field.
     * @return $this
     */
    public function setField48($field48)
    {
        
        $this->field48 = $field48;
        return $this;
    }
    
    /**
     * Gets field49
     * @return string
     */
    public function getField49()
    {
        return $this->field49;
    }
  
    /**
     * Sets field49
     * @param string $field49 Merchant defined field.
     * @return $this
     */
    public function setField49($field49)
    {
        
        $this->field49 = $field49;
        return $this;
    }
    
    /**
     * Gets field50
     * @return string
     */
    public function getField50()
    {
        return $this->field50;
    }
  
    /**
     * Sets field50
     * @param string $field50 Merchant defined field.
     * @return $this
     */
    public function setField50($field50)
    {
        
        $this->field50 = $field50;
        return $this;
    }
    
    /**
     * Gets field51
     * @return string
     */
    public function getField51()
    {
        return $this->field51;
    }
  
    /**
     * Sets field51
     * @param string $field51 Merchant defined field.
     * @return $this
     */
    public function setField51($field51)
    {
        
        $this->field51 = $field51;
        return $this;
    }
    
    /**
     * Gets field52
     * @return string
     */
    public function getField52()
    {
        return $this->field52;
    }
  
    /**
     * Sets field52
     * @param string $field52 Merchant defined field.
     * @return $this
     */
    public function setField52($field52)
    {
        
        $this->field52 = $field52;
        return $this;
    }
    
    /**
     * Gets field53
     * @return string
     */
    public function getField53()
    {
        return $this->field53;
    }
  
    /**
     * Sets field53
     * @param string $field53 Merchant defined field.
     * @return $this
     */
    public function setField53($field53)
    {
        
        $this->field53 = $field53;
        return $this;
    }
    
    /**
     * Gets field54
     * @return string
     */
    public function getField54()
    {
        return $this->field54;
    }
  
    /**
     * Sets field54
     * @param string $field54 Merchant defined field.
     * @return $this
     */
    public function setField54($field54)
    {
        
        $this->field54 = $field54;
        return $this;
    }
    
    /**
     * Gets field55
     * @return string
     */
    public function getField55()
    {
        return $this->field55;
    }
  
    /**
     * Sets field55
     * @param string $field55 Merchant defined field.
     * @return $this
     */
    public function setField55($field55)
    {
        
        $this->field55 = $field55;
        return $this;
    }
    
    /**
     * Gets field56
     * @return string
     */
    public function getField56()
    {
        return $this->field56;
    }
  
    /**
     * Sets field56
     * @param string $field56 Merchant defined field.
     * @return $this
     */
    public function setField56($field56)
    {
        
        $this->field56 = $field56;
        return $this;
    }
    
    /**
     * Gets field57
     * @return string
     */
    public function getField57()
    {
        return $this->field57;
    }
  
    /**
     * Sets field57
     * @param string $field57 Merchant defined field.
     * @return $this
     */
    public function setField57($field57)
    {
        
        $this->field57 = $field57;
        return $this;
    }
    
    /**
     * Gets field58
     * @return string
     */
    public function getField58()
    {
        return $this->field58;
    }
  
    /**
     * Sets field58
     * @param string $field58 Merchant defined field.
     * @return $this
     */
    public function setField58($field58)
    {
        
        $this->field58 = $field58;
        return $this;
    }
    
    /**
     * Gets field59
     * @return string
     */
    public function getField59()
    {
        return $this->field59;
    }
  
    /**
     * Sets field59
     * @param string $field59 Merchant defined field.
     * @return $this
     */
    public function setField59($field59)
    {
        
        $this->field59 = $field59;
        return $this;
    }
    
    /**
     * Gets field60
     * @return string
     */
    public function getField60()
    {
        return $this->field60;
    }
  
    /**
     * Sets field60
     * @param string $field60 Merchant defined field.
     * @return $this
     */
    public function setField60($field60)
    {
        
        $this->field60 = $field60;
        return $this;
    }
    
    /**
     * Gets field61
     * @return string
     */
    public function getField61()
    {
        return $this->field61;
    }
  
    /**
     * Sets field61
     * @param string $field61 Merchant defined field.
     * @return $this
     */
    public function setField61($field61)
    {
        
        $this->field61 = $field61;
        return $this;
    }
    
    /**
     * Gets field62
     * @return string
     */
    public function getField62()
    {
        return $this->field62;
    }
  
    /**
     * Sets field62
     * @param string $field62 Merchant defined field.
     * @return $this
     */
    public function setField62($field62)
    {
        
        $this->field62 = $field62;
        return $this;
    }
    
    /**
     * Gets field63
     * @return string
     */
    public function getField63()
    {
        return $this->field63;
    }
  
    /**
     * Sets field63
     * @param string $field63 Merchant defined field.
     * @return $this
     */
    public function setField63($field63)
    {
        
        $this->field63 = $field63;
        return $this;
    }
    
    /**
     * Gets field64
     * @return string
     */
    public function getField64()
    {
        return $this->field64;
    }
  
    /**
     * Sets field64
     * @param string $field64 Merchant defined field.
     * @return $this
     */
    public function setField64($field64)
    {
        
        $this->field64 = $field64;
        return $this;
    }
    
    /**
     * Gets field65
     * @return string
     */
    public function getField65()
    {
        return $this->field65;
    }
  
    /**
     * Sets field65
     * @param string $field65 Merchant defined field.
     * @return $this
     */
    public function setField65($field65)
    {
        
        $this->field65 = $field65;
        return $this;
    }
    
    /**
     * Gets field66
     * @return string
     */
    public function getField66()
    {
        return $this->field66;
    }
  
    /**
     * Sets field66
     * @param string $field66 Merchant defined field.
     * @return $this
     */
    public function setField66($field66)
    {
        
        $this->field66 = $field66;
        return $this;
    }
    
    /**
     * Gets field67
     * @return string
     */
    public function getField67()
    {
        return $this->field67;
    }
  
    /**
     * Sets field67
     * @param string $field67 Merchant defined field.
     * @return $this
     */
    public function setField67($field67)
    {
        
        $this->field67 = $field67;
        return $this;
    }
    
    /**
     * Gets field68
     * @return string
     */
    public function getField68()
    {
        return $this->field68;
    }
  
    /**
     * Sets field68
     * @param string $field68 Merchant defined field.
     * @return $this
     */
    public function setField68($field68)
    {
        
        $this->field68 = $field68;
        return $this;
    }
    
    /**
     * Gets field69
     * @return string
     */
    public function getField69()
    {
        return $this->field69;
    }
  
    /**
     * Sets field69
     * @param string $field69 Merchant defined field.
     * @return $this
     */
    public function setField69($field69)
    {
        
        $this->field69 = $field69;
        return $this;
    }
    
    /**
     * Gets field70
     * @return string
     */
    public function getField70()
    {
        return $this->field70;
    }
  
    /**
     * Sets field70
     * @param string $field70 Merchant defined field.
     * @return $this
     */
    public function setField70($field70)
    {
        
        $this->field70 = $field70;
        return $this;
    }
    
    /**
     * Gets field71
     * @return string
     */
    public function getField71()
    {
        return $this->field71;
    }
  
    /**
     * Sets field71
     * @param string $field71 Merchant defined field.
     * @return $this
     */
    public function setField71($field71)
    {
        
        $this->field71 = $field71;
        return $this;
    }
    
    /**
     * Gets field72
     * @return string
     */
    public function getField72()
    {
        return $this->field72;
    }
  
    /**
     * Sets field72
     * @param string $field72 Merchant defined field.
     * @return $this
     */
    public function setField72($field72)
    {
        
        $this->field72 = $field72;
        return $this;
    }
    
    /**
     * Gets field73
     * @return string
     */
    public function getField73()
    {
        return $this->field73;
    }
  
    /**
     * Sets field73
     * @param string $field73 Merchant defined field.
     * @return $this
     */
    public function setField73($field73)
    {
        
        $this->field73 = $field73;
        return $this;
    }
    
    /**
     * Gets field74
     * @return string
     */
    public function getField74()
    {
        return $this->field74;
    }
  
    /**
     * Sets field74
     * @param string $field74 Merchant defined field.
     * @return $this
     */
    public function setField74($field74)
    {
        
        $this->field74 = $field74;
        return $this;
    }
    
    /**
     * Gets field75
     * @return string
     */
    public function getField75()
    {
        return $this->field75;
    }
  
    /**
     * Sets field75
     * @param string $field75 Merchant defined field.
     * @return $this
     */
    public function setField75($field75)
    {
        
        $this->field75 = $field75;
        return $this;
    }
    
    /**
     * Gets field76
     * @return string
     */
    public function getField76()
    {
        return $this->field76;
    }
  
    /**
     * Sets field76
     * @param string $field76 Merchant defined field.
     * @return $this
     */
    public function setField76($field76)
    {
        
        $this->field76 = $field76;
        return $this;
    }
    
    /**
     * Gets field77
     * @return string
     */
    public function getField77()
    {
        return $this->field77;
    }
  
    /**
     * Sets field77
     * @param string $field77 Merchant defined field.
     * @return $this
     */
    public function setField77($field77)
    {
        
        $this->field77 = $field77;
        return $this;
    }
    
    /**
     * Gets field78
     * @return string
     */
    public function getField78()
    {
        return $this->field78;
    }
  
    /**
     * Sets field78
     * @param string $field78 Merchant defined field.
     * @return $this
     */
    public function setField78($field78)
    {
        
        $this->field78 = $field78;
        return $this;
    }
    
    /**
     * Gets field79
     * @return string
     */
    public function getField79()
    {
        return $this->field79;
    }
  
    /**
     * Sets field79
     * @param string $field79 Merchant defined field.
     * @return $this
     */
    public function setField79($field79)
    {
        
        $this->field79 = $field79;
        return $this;
    }
    
    /**
     * Gets field80
     * @return string
     */
    public function getField80()
    {
        return $this->field80;
    }
  
    /**
     * Sets field80
     * @param string $field80 Merchant defined field.
     * @return $this
     */
    public function setField80($field80)
    {
        
        $this->field80 = $field80;
        return $this;
    }
    
    /**
     * Gets field81
     * @return string
     */
    public function getField81()
    {
        return $this->field81;
    }
  
    /**
     * Sets field81
     * @param string $field81 Merchant defined field.
     * @return $this
     */
    public function setField81($field81)
    {
        
        $this->field81 = $field81;
        return $this;
    }
    
    /**
     * Gets field82
     * @return string
     */
    public function getField82()
    {
        return $this->field82;
    }
  
    /**
     * Sets field82
     * @param string $field82 Merchant defined field.
     * @return $this
     */
    public function setField82($field82)
    {
        
        $this->field82 = $field82;
        return $this;
    }
    
    /**
     * Gets field83
     * @return string
     */
    public function getField83()
    {
        return $this->field83;
    }
  
    /**
     * Sets field83
     * @param string $field83 Merchant defined field.
     * @return $this
     */
    public function setField83($field83)
    {
        
        $this->field83 = $field83;
        return $this;
    }
    
    /**
     * Gets field84
     * @return string
     */
    public function getField84()
    {
        return $this->field84;
    }
  
    /**
     * Sets field84
     * @param string $field84 Merchant defined field.
     * @return $this
     */
    public function setField84($field84)
    {
        
        $this->field84 = $field84;
        return $this;
    }
    
    /**
     * Gets field85
     * @return string
     */
    public function getField85()
    {
        return $this->field85;
    }
  
    /**
     * Sets field85
     * @param string $field85 Merchant defined field.
     * @return $this
     */
    public function setField85($field85)
    {
        
        $this->field85 = $field85;
        return $this;
    }
    
    /**
     * Gets field86
     * @return string
     */
    public function getField86()
    {
        return $this->field86;
    }
  
    /**
     * Sets field86
     * @param string $field86 Merchant defined field.
     * @return $this
     */
    public function setField86($field86)
    {
        
        $this->field86 = $field86;
        return $this;
    }
    
    /**
     * Gets field87
     * @return string
     */
    public function getField87()
    {
        return $this->field87;
    }
  
    /**
     * Sets field87
     * @param string $field87 Merchant defined field.
     * @return $this
     */
    public function setField87($field87)
    {
        
        $this->field87 = $field87;
        return $this;
    }
    
    /**
     * Gets field88
     * @return string
     */
    public function getField88()
    {
        return $this->field88;
    }
  
    /**
     * Sets field88
     * @param string $field88 Merchant defined field.
     * @return $this
     */
    public function setField88($field88)
    {
        
        $this->field88 = $field88;
        return $this;
    }
    
    /**
     * Gets field89
     * @return string
     */
    public function getField89()
    {
        return $this->field89;
    }
  
    /**
     * Sets field89
     * @param string $field89 Merchant defined field.
     * @return $this
     */
    public function setField89($field89)
    {
        
        $this->field89 = $field89;
        return $this;
    }
    
    /**
     * Gets field90
     * @return string
     */
    public function getField90()
    {
        return $this->field90;
    }
  
    /**
     * Sets field90
     * @param string $field90 Merchant defined field.
     * @return $this
     */
    public function setField90($field90)
    {
        
        $this->field90 = $field90;
        return $this;
    }
    
    /**
     * Gets field91
     * @return string
     */
    public function getField91()
    {
        return $this->field91;
    }
  
    /**
     * Sets field91
     * @param string $field91 Merchant defined field.
     * @return $this
     */
    public function setField91($field91)
    {
        
        $this->field91 = $field91;
        return $this;
    }
    
    /**
     * Gets field92
     * @return string
     */
    public function getField92()
    {
        return $this->field92;
    }
  
    /**
     * Sets field92
     * @param string $field92 Merchant defined field.
     * @return $this
     */
    public function setField92($field92)
    {
        
        $this->field92 = $field92;
        return $this;
    }
    
    /**
     * Gets field93
     * @return string
     */
    public function getField93()
    {
        return $this->field93;
    }
  
    /**
     * Sets field93
     * @param string $field93 Merchant defined field.
     * @return $this
     */
    public function setField93($field93)
    {
        
        $this->field93 = $field93;
        return $this;
    }
    
    /**
     * Gets field94
     * @return string
     */
    public function getField94()
    {
        return $this->field94;
    }
  
    /**
     * Sets field94
     * @param string $field94 Merchant defined field.
     * @return $this
     */
    public function setField94($field94)
    {
        
        $this->field94 = $field94;
        return $this;
    }
    
    /**
     * Gets field95
     * @return string
     */
    public function getField95()
    {
        return $this->field95;
    }
  
    /**
     * Sets field95
     * @param string $field95 Merchant defined field.
     * @return $this
     */
    public function setField95($field95)
    {
        
        $this->field95 = $field95;
        return $this;
    }
    
    /**
     * Gets field96
     * @return string
     */
    public function getField96()
    {
        return $this->field96;
    }
  
    /**
     * Sets field96
     * @param string $field96 Merchant defined field.
     * @return $this
     */
    public function setField96($field96)
    {
        
        $this->field96 = $field96;
        return $this;
    }
    
    /**
     * Gets field97
     * @return string
     */
    public function getField97()
    {
        return $this->field97;
    }
  
    /**
     * Sets field97
     * @param string $field97 Merchant defined field.
     * @return $this
     */
    public function setField97($field97)
    {
        
        $this->field97 = $field97;
        return $this;
    }
    
    /**
     * Gets field98
     * @return string
     */
    public function getField98()
    {
        return $this->field98;
    }
  
    /**
     * Sets field98
     * @param string $field98 Merchant defined field.
     * @return $this
     */
    public function setField98($field98)
    {
        
        $this->field98 = $field98;
        return $this;
    }
    
    /**
     * Gets field99
     * @return string
     */
    public function getField99()
    {
        return $this->field99;
    }
  
    /**
     * Sets field99
     * @param string $field99 Merchant defined field.
     * @return $this
     */
    public function setField99($field99)
    {
        
        $this->field99 = $field99;
        return $this;
    }
    
    /**
     * Gets field100
     * @return string
     */
    public function getField100()
    {
        return $this->field100;
    }
  
    /**
     * Sets field100
     * @param string $field100 Merchant defined field.
     * @return $this
     */
    public function setField100($field100)
    {
        
        $this->field100 = $field100;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
