<?php
/**
 * Offer
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;
/**
 * Offer Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     CyberSource
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Offer implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'product_sku' => 'string',
        'quantity' => 'string',
        'unit_price' => 'string',
        'tax_amount' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'product_sku' => 'productSKU',
        'quantity' => 'quantity',
        'unit_price' => 'unitPrice',
        'tax_amount' => 'taxAmount'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'product_sku' => 'setProductSku',
        'quantity' => 'setQuantity',
        'unit_price' => 'setUnitPrice',
        'tax_amount' => 'setTaxAmount'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'product_sku' => 'getProductSku',
        'quantity' => 'getQuantity',
        'unit_price' => 'getUnitPrice',
        'tax_amount' => 'getTaxAmount'
    );
  
    
    /**
      * $product_sku Product SKU
      * @var string
      */
    protected $product_sku;
    
    /**
      * $quantity Quantity.
      * @var string
      */
    protected $quantity;
    
    /**
      * $unit_price Unit Price.
      * @var string
      */
    protected $unit_price;
    
    /**
      * $tax_amount Tax Amount.
      * @var string
      */
    protected $tax_amount;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->product_sku = $data["product_sku"];
            $this->quantity = $data["quantity"];
            $this->unit_price = $data["unit_price"];
            $this->tax_amount = $data["tax_amount"];
        }
    }
    
    /**
     * Gets product_sku
     * @return string
     */
    public function getProductSku()
    {
        return $this->product_sku;
    }
  
    /**
     * Sets product_sku
     * @param string $product_sku Product SKU
     * @return $this
     */
    public function setProductSku($product_sku)
    {
        
        $this->product_sku = $product_sku;
        return $this;
    }
    
    /**
     * Gets quantity
     * @return string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }
  
    /**
     * Sets quantity
     * @param string $quantity Quantity.
     * @return $this
     */
    public function setQuantity($quantity)
    {
        
        $this->quantity = $quantity;
        return $this;
    }
    
    /**
     * Gets unit_price
     * @return string
     */
    public function getUnitPrice()
    {
        return $this->unit_price;
    }
  
    /**
     * Sets unit_price
     * @param string $unit_price Unit Price.
     * @return $this
     */
    public function setUnitPrice($unit_price)
    {
        
        $this->unit_price = $unit_price;
        return $this;
    }
    
    /**
     * Gets tax_amount
     * @return string
     */
    public function getTaxAmount()
    {
        return $this->tax_amount;
    }
  
    /**
     * Sets tax_amount
     * @param string $tax_amount Tax Amount.
     * @return $this
     */
    public function setTaxAmount($tax_amount)
    {
        
        $this->tax_amount = $tax_amount;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
