<?php
/**
 * TransactionRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;
/**
 * TransactionRequest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     CyberSource
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionRequest implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'merchant_id' => 'string',
        'reference_id' => 'string',
        'type' => 'string',
        'amount' => 'string',
        'currency' => 'string',
        'card_number' => 'string',
        'card_expiration_month' => 'string',
        'card_expiration_year' => 'string',
        'bill_to' => '\CyberSource\Model\BillTo'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'merchant_id' => 'merchantId',
        'reference_id' => 'referenceId',
        'type' => 'type',
        'amount' => 'amount',
        'currency' => 'currency',
        'card_number' => 'cardNumber',
        'card_expiration_month' => 'cardExpirationMonth',
        'card_expiration_year' => 'cardExpirationYear',
        'bill_to' => 'billTo'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'merchant_id' => 'setMerchantId',
        'reference_id' => 'setReferenceId',
        'type' => 'setType',
        'amount' => 'setAmount',
        'currency' => 'setCurrency',
        'card_number' => 'setCardNumber',
        'card_expiration_month' => 'setCardExpirationMonth',
        'card_expiration_year' => 'setCardExpirationYear',
        'bill_to' => 'setBillTo'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'merchant_id' => 'getMerchantId',
        'reference_id' => 'getReferenceId',
        'type' => 'getType',
        'amount' => 'getAmount',
        'currency' => 'getCurrency',
        'card_number' => 'getCardNumber',
        'card_expiration_month' => 'getCardExpirationMonth',
        'card_expiration_year' => 'getCardExpirationYear',
        'bill_to' => 'getBillTo'
    );
  
    
    /**
      * $merchant_id Merchant identifier
      * @var string
      */
    protected $merchant_id;
    
    /**
      * $reference_id Merchant reference ID for the transaction.
      * @var string
      */
    protected $reference_id;
    
    /**
      * $type Transaction type.  E.g. sale, auth, capture
      * @var string
      */
    protected $type;
    
    /**
      * $amount Total amount
      * @var string
      */
    protected $amount;
    
    /**
      * $currency The currency used for the transaction
      * @var string
      */
    protected $currency;
    
    /**
      * $card_number Credit card number
      * @var string
      */
    protected $card_number;
    
    /**
      * $card_expiration_month Two digit expiration month
      * @var string
      */
    protected $card_expiration_month;
    
    /**
      * $card_expiration_year Four digit expiration year
      * @var string
      */
    protected $card_expiration_year;
    
    /**
      * $bill_to 
      * @var \CyberSource\Model\BillTo
      */
    protected $bill_to;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->merchant_id = $data["merchant_id"];
            $this->reference_id = $data["reference_id"];
            $this->type = $data["type"];
            $this->amount = $data["amount"];
            $this->currency = $data["currency"];
            $this->card_number = $data["card_number"];
            $this->card_expiration_month = $data["card_expiration_month"];
            $this->card_expiration_year = $data["card_expiration_year"];
            $this->bill_to = $data["bill_to"];
        }
    }
    
    /**
     * Gets merchant_id
     * @return string
     */
    public function getMerchantId()
    {
        return $this->merchant_id;
    }
  
    /**
     * Sets merchant_id
     * @param string $merchant_id Merchant identifier
     * @return $this
     */
    public function setMerchantId($merchant_id)
    {
        
        $this->merchant_id = $merchant_id;
        return $this;
    }
    
    /**
     * Gets reference_id
     * @return string
     */
    public function getReferenceId()
    {
        return $this->reference_id;
    }
  
    /**
     * Sets reference_id
     * @param string $reference_id Merchant reference ID for the transaction.
     * @return $this
     */
    public function setReferenceId($reference_id)
    {
        
        $this->reference_id = $reference_id;
        return $this;
    }
    
    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }
  
    /**
     * Sets type
     * @param string $type Transaction type.  E.g. sale, auth, capture
     * @return $this
     */
    public function setType($type)
    {
        
        $this->type = $type;
        return $this;
    }
    
    /**
     * Gets amount
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }
  
    /**
     * Sets amount
     * @param string $amount Total amount
     * @return $this
     */
    public function setAmount($amount)
    {
        
        $this->amount = $amount;
        return $this;
    }
    
    /**
     * Gets currency
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }
  
    /**
     * Sets currency
     * @param string $currency The currency used for the transaction
     * @return $this
     */
    public function setCurrency($currency)
    {
        
        $this->currency = $currency;
        return $this;
    }
    
    /**
     * Gets card_number
     * @return string
     */
    public function getCardNumber()
    {
        return $this->card_number;
    }
  
    /**
     * Sets card_number
     * @param string $card_number Credit card number
     * @return $this
     */
    public function setCardNumber($card_number)
    {
        
        $this->card_number = $card_number;
        return $this;
    }
    
    /**
     * Gets card_expiration_month
     * @return string
     */
    public function getCardExpirationMonth()
    {
        return $this->card_expiration_month;
    }
  
    /**
     * Sets card_expiration_month
     * @param string $card_expiration_month Two digit expiration month
     * @return $this
     */
    public function setCardExpirationMonth($card_expiration_month)
    {
        
        $this->card_expiration_month = $card_expiration_month;
        return $this;
    }
    
    /**
     * Gets card_expiration_year
     * @return string
     */
    public function getCardExpirationYear()
    {
        return $this->card_expiration_year;
    }
  
    /**
     * Sets card_expiration_year
     * @param string $card_expiration_year Four digit expiration year
     * @return $this
     */
    public function setCardExpirationYear($card_expiration_year)
    {
        
        $this->card_expiration_year = $card_expiration_year;
        return $this;
    }
    
    /**
     * Gets bill_to
     * @return \CyberSource\Model\BillTo
     */
    public function getBillTo()
    {
        return $this->bill_to;
    }
  
    /**
     * Sets bill_to
     * @param \CyberSource\Model\BillTo $bill_to 
     * @return $this
     */
    public function setBillTo($bill_to)
    {
        
        $this->bill_to = $bill_to;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
